version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: server-scripts/install.sh
      timeout: 300
      runas: ubuntu
    - location: server-scripts/start-apache.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: server-scripts/stop-apache.sh
      timeout: 300
      runas: ubuntu
